### ISSUE TITLE
Include mimetype for "Other" mimetypes

### ISSUE THREAD

**Issue by FabienHenon** [danyx23/elm-mimetype#5]
Hi,

Thank you for this package. I know it would be tough to handle every possible mimetype, but I think a little improvement in your library would be nice: by including the mimetype as string for "Other" mimetypes.

For instance, `text/csv` mimetype is not handled, but instead of having:

```elm
parseMimeType "text/csv" == Just (Text OtherText)
```

I think it would be nicer to have:

```elm
parseMimeType "text/csv" == Just (Text (OtherText "csv"))
```

This way the user can still make some checks on the parsed mimetype even if it's not supported.
Also, it would allow the user to call `toString` on this `Text (OtherText "csv")` to get `"text/csv"`

**Comment by danyx23** [comment]
Sounds good! Do you feel like implelementing this? It's not a big deal but I have lot's of other stuff going on right now.

**Comment by FabienHenon** [comment]
No problem, I'll submit that this afternoon (French time), I already wrote the code for this in my project

**Comment by danyx23** [comment]
Thanks! I just published an updated version
